spring:
  datasource:
    username: admin
    url: jdbc:mysql://mentaltaldb.cezdgu2xim5u.ap-northeast-2.rds.amazonaws.com/dbmentaltal
    password: apsxkfxkf
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

mail:
  address:
    admin: sangw12477@gmail.com
jwt:
  key: main301234567890q1w2e3r4a1s2d3fg5h61579024628510284759j032958209341753-0456912443639minoiaefqwefteabongqdfasdfhuijujinasdfwegyerinzsfdfwefhaejeongafewogafdgimhaeafdeasgdasfmerong     # GITHUB의 환경변수에서 가져오도록 수정하면 자동배포시 적용됨스
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420